name: Running tests workflow

on: [push]

jobs:

  test:
    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: pnpm ci
      - run: pnpm test
